{% set name = "xpublish-edr" %}
{% set version = "0.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/xpublish_edr-{{ version }}.tar.gz
  sha256: cbb9c01b46fb3b97a8f0a7d9fce75822a0b3cb15f25d0afac7c7a49b8cd21b08

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=61
    - wheel
    - setuptools-scm >=3.4
    - pip
  run:
    - python >={{ python_min }}
    - scipy
    - shapely
    - xarray
    - xpublish <0.4.0,>=0.3.0

test:
  imports:
    - xpublish_edr
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/xpublish-community/xpublish-edr
  summary: Xpublish plugin for the OGC EDR API
  license: BSD-3-Clause
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - abkfenris
